insert into public.projects (
  title,
  category,
  status,
  short_description,
  full_description,
  asking_price,
  monthly_revenue,
  monthly_profit,
  revenue_multiple,
  monetization_model,
  business_model,
  monthly_traffic,
  total_users,
  app_installs,
  growth_rate,
  founded_year,
  team_size,
  tech_stack,
  what_is_included,
  growth_opportunities,
  risks_and_notes,
  image_url,
  is_featured
)
values
(
  'CloudSync AI',
  'saas',
  'active',
  'AI-powered cloud data synchronization platform serving enterprise clients.',
  'CloudSync AI is a mature B2B SaaS platform that provides enterprise-grade data synchronization across cloud services. Built on a modern microservices architecture, the platform handles high daily data sync volume and serves a stable customer base.',
  4200000,
  182000,
  127000,
  1.9,
  'Subscription (Annual + Monthly)',
  'B2B SaaS',
  95000,
  2400,
  null,
  12.4,
  2021,
  8,
  array['React', 'Node.js', 'Python', 'PostgreSQL', 'Redis', 'Kubernetes'],
  array['Full source code', 'Brand assets', 'Domain', 'Customer database', 'SOC 2 certification transfer', '3-month technical transition support'],
  'Enterprise sales expansion into APAC market. New vertical-specific solutions for healthcare and finance. API marketplace for third-party integrations.',
  'Dependency on major cloud provider APIs. Competition from larger players entering the space. Key technical team retention during transition.',
  '',
  true
),
(
  'StorePilot',
  'ecommerce',
  'active',
  'Outdoor and hiking niche e-commerce brand with loyal repeat customers.',
  'StorePilot is a well-established e-commerce brand in the outdoor and hiking niche. The business runs on Shopify, has repeat buyers, stable supplier relationships, and clear growth opportunities through wholesale and subscriptions.',
  1200000,
  31000,
  19500,
  3.2,
  'Direct Sales',
  'DTC E-commerce',
  74000,
  18500,
  null,
  8.1,
  2021,
  3,
  array['Shopify', 'Klaviyo', 'Meta Ads', 'Google Ads'],
  array['Shopify store', 'Customer and order data', 'Supplier contacts', 'Social media accounts', 'Email list', 'Brand assets'],
  'Launch subscription box. Expand into Amazon. Develop loyalty program and wholesale distribution.',
  'Seasonal demand fluctuations. Margin sensitivity to shipping costs. Supplier concentration risk.',
  '',
  true
),
(
  'NestMetrics',
  'saas',
  'active',
  'Analytics and reporting platform for property managers and landlords.',
  'NestMetrics helps property managers track occupancy, maintenance costs, and revenue across multiple properties. The product serves a growing niche with recurring revenue and low churn.',
  340000,
  8500,
  5200,
  3.4,
  'Monthly Subscription',
  'Vertical SaaS',
  12000,
  2400,
  null,
  9.7,
  2024,
  2,
  array['Vue', 'Node.js', 'PostgreSQL'],
  array['Full codebase', 'Customer accounts', 'Analytics dashboard', 'Documentation'],
  'Add AI forecasting. Expand to commercial real estate. Add mobile companion app.',
  'Small team concentration. Long enterprise sales cycles. Regulatory differences by region.',
  '',
  false
),
(
  'SendLoop',
  'saas',
  'under-offer',
  'Email automation platform for e-commerce brands with deep integrations.',
  'SendLoop is an email automation tool focused on DTC brands. It offers advanced segmentation, flow automation, and strong native integrations for Shopify and WooCommerce.',
  2100000,
  68000,
  41000,
  2.6,
  'Monthly + Annual Subscription',
  'Martech SaaS',
  95000,
  8600,
  null,
  15.7,
  2020,
  7,
  array['React', 'Node.js', 'PostgreSQL', 'AWS'],
  array['SaaS codebase', 'Customer data', 'Infrastructure', 'Runbooks', 'Partner agreements'],
  'Launch SMS and WhatsApp automation. Add AI assistant. Expand upmarket.',
  'Deliverability risk. Dependence on platform integrations. Competitive martech market.',
  '',
  true
),
(
  'AdFlow Pro',
  'ai-tools',
  'active',
  'Ad creative and campaign tracking platform for marketing agencies.',
  'AdFlow Pro centralizes campaign performance across Meta, Google, and TikTok while helping agencies manage creatives and reporting from one dashboard.',
  780000,
  22400,
  14800,
  2.9,
  'Subscription',
  'Agency SaaS',
  41000,
  5200,
  null,
  11.3,
  2024,
  4,
  array['React', 'TypeScript', 'Node.js', 'BigQuery'],
  array['App source code', 'Client accounts', 'Reporting templates', 'Brand assets'],
  'White-label offering. API-based reporting marketplace. Enterprise agency expansion.',
  'Ad platform API changes. High expectations for reporting accuracy. Agency churn risk.',
  '',
  false
),
(
  'PageCraft',
  'saas',
  'active',
  'No-code landing page builder for indie makers and solo founders.',
  'PageCraft is a lightweight no-code landing page builder with a simple editor, template marketplace, and strong retention among solo founders.',
  560000,
  17600,
  11200,
  2.7,
  'Monthly Subscription',
  'SaaS',
  34000,
  3800,
  null,
  10.8,
  2023,
  3,
  array['Vue', 'Node.js', 'Supabase'],
  array['Builder app', 'Templates', 'Customer data', 'Marketing site'],
  'Launch AI copy generation. Add premium templates. Partner with creator communities.',
  'Competitive market. Need for strong differentiation. Template quality dependency.',
  '',
  false
),
(
  'GearVault',
  'ecommerce',
  'active',
  'Premium cycling accessories brand with healthy repeat purchase behavior.',
  'GearVault is a curated e-commerce brand focused on cycling accessories. It has a recognizable niche audience, strong supplier relationships, and stable repeat demand.',
  890000,
  24000,
  13800,
  3.1,
  'Direct Sales',
  'E-commerce Brand',
  52000,
  12400,
  null,
  7.4,
  2022,
  4,
  array['Shopify', 'Klaviyo', 'GA4'],
  array['Storefront', 'Customer data', 'Brand assets', 'Supplier contacts'],
  'Expand into bundles. Launch ambassador program. Build subscription for maintenance kits.',
  'Inventory risk. Logistics costs. Brand growth depends on niche audience expansion.',
  '',
  false
),
(
  'PromptStack',
  'ai-tools',
  'draft',
  'Marketplace for curated AI prompt templates with passive revenue dynamics.',
  'PromptStack connects creators and buyers of high-quality AI prompt templates. The marketplace benefits from community contributions and low operational complexity.',
  195000,
  5800,
  4100,
  2.4,
  'Marketplace Commission',
  'Marketplace',
  19000,
  3100,
  null,
  18.6,
  2025,
  1,
  array['Next.js', 'Stripe', 'PostgreSQL'],
  array['Marketplace app', 'Prompt catalog', 'Contributor accounts'],
  'Expand into enterprise prompt packs. Add subscriptions. Launch private team workspaces.',
  'Rapid category saturation. Moderation overhead. Platform dependency on AI trends.',
  '',
  false
),
(
  'FinScope Weekly',
  'content',
  'active',
  'Fintech newsletter with sponsorship revenue and paid subscriber tier.',
  'FinScope Weekly is a curated fintech newsletter with a strong open rate, sponsorship revenue, and a growing paid tier audience.',
  310000,
  9200,
  7600,
  2.8,
  'Sponsorship + Paid Membership',
  'Newsletter Media',
  22000,
  11000,
  null,
  6.2,
  2023,
  2,
  array['Beehiiv', 'Notion', 'Stripe'],
  array['Newsletter brand', 'Subscriber list', 'Sponsor relationships', 'Content archive'],
  'Launch premium research tier. Expand into podcast and webinars. Build B2B sponsorship packages.',
  'Audience fatigue. Reliance on sponsorship market. Founder brand dependency.',
  '',
  false
),
(
  'DevCircle',
  'communities',
  'active',
  'Paid community for senior software engineers with cohorts and job board.',
  'DevCircle is a premium professional community with recurring membership revenue, cohort-based programs, and partner sponsorship opportunities.',
  430000,
  13500,
  9800,
  2.5,
  'Membership + Sponsorship',
  'Community Platform',
  16000,
  1400,
  null,
  9.9,
  2024,
  2,
  array['Circle', 'Stripe', 'Webflow'],
  array['Community platform', 'Member database', 'Sponsor contacts', 'Content library'],
  'Corporate memberships. Premium mentoring. Recruiting partnerships.',
  'Community engagement must remain high. Founder-led content risk. Churn sensitivity.',
  '',
  false
),
(
  'TabFlow',
  'browser-extensions',
  'active',
  'Workspace and tab management browser extension with freemium monetization.',
  'TabFlow is a browser extension for productivity-focused users managing tabs, sessions, and workspaces, with a growing paid subscriber base.',
  240000,
  7100,
  5600,
  2.3,
  'Freemium + Subscription',
  'Browser Extension SaaS',
  48000,
  8600,
  80000,
  13.1,
  2024,
  2,
  array['TypeScript', 'Chrome APIs', 'Firebase'],
  array['Extension codebase', 'User analytics', 'Brand assets'],
  'Expand to Edge and Firefox. Add team workspaces. Launch lifetime plan.',
  'Browser platform changes. Conversion rate optimization needed. Limited moat.',
  '',
  false
),
(
  'FitTrack Mobile',
  'mobile-apps',
  'active',
  'Fitness tracking mobile app with social features and in-app purchases.',
  'FitTrack Mobile is a cross-platform fitness app with workout logging, streaks, habit tracking, and community engagement loops.',
  620000,
  18900,
  12400,
  2.7,
  'Subscription + In-App Purchases',
  'Mobile App',
  0,
  24000,
  120000,
  14.8,
  2023,
  5,
  array['React Native', 'Firebase', 'Node.js'],
  array['iOS app', 'Android app', 'Backend', 'User data', 'Brand assets'],
  'Corporate wellness plans. Premium coaching layer. Wearable integrations.',
  'App store policy risk. Paid acquisition costs. Retention pressure in health apps.',
  '',
  false
),
(
  'UIBundle',
  'digital-products',
  'active',
  'Digital storefront with Figma UI kits, icon packs, and design templates.',
  'UIBundle sells design assets through one-time purchases and bundles, with low overhead and highly passive operations.',
  160000,
  4800,
  4200,
  2.1,
  'One-Time Purchases',
  'Digital Products',
  28000,
  0,
  null,
  5.5,
  2024,
  1,
  array['Gumroad', 'Figma', 'Framer'],
  array['Digital catalog', 'Customer list', 'Brand assets', 'Product files'],
  'Subscription access pass. Team licenses. Affiliate program.',
  'Marketplace competition. Piracy. Requires regular new asset releases.',
  '',
  false
),
(
  'LocalMart',
  'marketplace',
  'active',
  'Regional marketplace connecting local producers with nearby buyers.',
  'LocalMart is a two-sided marketplace for artisan producers and regional buyers, operating in a limited geographic footprint with clear expansion room.',
  750000,
  21000,
  11500,
  2.8,
  'Marketplace Commission',
  'Local Marketplace',
  37000,
  9200,
  null,
  10.1,
  2023,
  6,
  array['Vue', 'Node.js', 'PostgreSQL', 'Stripe'],
  array['Marketplace platform', 'Vendor network', 'Buyer database', 'Operations docs'],
  'Expand to more cities. Add subscriptions for sellers. Introduce logistics partnerships.',
  'Supply-demand balance risk. Local ops complexity. Regional expansion execution risk.',
  '',
  false
),
(
  'EcoCart',
  'ecommerce',
  'active',
  'Eco-friendly household products brand with repeat buyers and subscriptions.',
  'EcoCart is a sustainability-focused e-commerce brand with strong brand identity, repeat orders, and a growing subscription box line.',
  480000,
  14600,
  8900,
  2.9,
  'Direct Sales + Subscription',
  'E-commerce Brand',
  31000,
  6800,
  null,
  8.7,
  2024,
  3,
  array['Shopify', 'Recharge', 'Klaviyo'],
  array['Storefront', 'Subscriber base', 'Supplier contacts', 'Brand assets'],
  'Wholesale opportunities. Product bundles. Subscription growth.',
  'Margin pressure. Supplier lead times. Greenwashing-sensitive audience expectations.',
  '',
  false
),
(
  'MetricForge',
  'saas',
  'active',
  'KPI dashboard and reporting software for startup finance teams.',
  'MetricForge helps finance teams centralize board metrics, runway tracking, and investor reporting in one dashboard.',
  540000,
  15800,
  10200,
  2.8,
  'Subscription',
  'B2B SaaS',
  26000,
  1800,
  null,
  11.9,
  2022,
  4,
  array['React', 'Node.js', 'PostgreSQL'],
  array['App source code', 'Customer accounts', 'Documentation'],
  'Enterprise plans. Benchmarking add-on. CFO advisory partnerships.',
  'Longer sales cycles. Need for financial trust and reliability.',
  '',
  false
),
(
  'CreatorLoop',
  'communities',
  'draft',
  'Private membership community for creators with workshops and peer groups.',
  'CreatorLoop offers a paid space for creators to access peer groups, workshops, and accountability programs.',
  275000,
  8700,
  6100,
  2.2,
  'Membership',
  'Community Business',
  11000,
  950,
  null,
  7.6,
  2024,
  2,
  array['Circle', 'Stripe', 'Notion'],
  array['Community assets', 'Member list', 'Workshop recordings'],
  'Corporate creator programs. Premium mastermind tier. Sponsorships.',
  'Member churn risk. Community moderation overhead. Founder-led growth dependency.',
  '',
  false
),
(
  'ClipBoost',
  'ai-tools',
  'active',
  'AI video clipping tool for creators and podcasters.',
  'ClipBoost transforms long-form video into short-form clips using AI scene detection and captioning, serving creators and agencies.',
  830000,
  26400,
  17300,
  3.0,
  'Subscription',
  'AI SaaS',
  62000,
  4200,
  null,
  19.4,
  2023,
  5,
  array['Python', 'FFmpeg', 'React', 'PostgreSQL'],
  array['AI pipeline', 'Web app', 'Customer data', 'Brand assets'],
  'Team collaboration features. Agency packages. API access.',
  'GPU cost sensitivity. Fast-moving AI market. Need for feature velocity.',
  '',
  false
),
(
  'LeadNest',
  'saas',
  'under-offer',
  'Lead capture and qualification platform for B2B service businesses.',
  'LeadNest helps agencies and service firms qualify incoming leads, enrich them, and automate follow-up workflows.',
  460000,
  13200,
  9100,
  2.6,
  'Subscription',
  'B2B SaaS',
  21000,
  1700,
  null,
  9.2,
  2022,
  3,
  array['Vue', 'Node.js', 'PostgreSQL'],
  array['App source code', 'Integrations', 'Customer list', 'SOPs'],
  'Partner channels. White-label version. CRM marketplace integrations.',
  'Dependence on lead source quality. SMB churn can affect retention.',
  '',
  false
),
(
  'CourseHarbor',
  'digital-products',
  'active',
  'Micro-course marketplace with evergreen educational bundles.',
  'CourseHarbor sells small digital courses and educational bundles across design, productivity, and freelancing niches.',
  225000,
  6900,
  5100,
  2.4,
  'One-Time Sales + Bundles',
  'Digital Education',
  18000,
  0,
  null,
  6.8,
  2023,
  2,
  array['Laravel', 'Stripe', 'PostgreSQL'],
  array['Marketplace site', 'Course catalog', 'Customer list', 'Instructor agreements'],
  'Subscription library. B2B learning packs. Affiliate expansion.',
  'Course quality consistency. Refund handling. Content freshness requirements.',
  '',
  false
);